name: Push to GitHub Pages

on:
  push:
    branches: [master]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  gh-pages-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: ./scripts/gh-pages-push.sh
