name: Deploy GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - run: |
          cd build
          git init
          git config user.email ${{ secrets.USER_EMAIL }}
          git config user.name "${{ secrets.USER_NAME }}"
          git remote add origin git@github.com:JoshuaVM95/JoshuaVM95.github.io.git
          git branch -M github-pages
          git add .
          git commit -m "Deploy"
          git push -u origin github-pages
